# plugin manager
[[plugins]]
repo = 'shougo/dein.vim'

# Color scheme
[[plugins]]
repo = 'icymind/NeoSolarized'

# Completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

# Tmux
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

# Fuzzy finder
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

# Filer
[[plugins]]
repo = 'Shougo/defx.nvim'

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# Status line
[[plugins]]
repo = 'vim-airline/vim-airline'

# Interface
[[plugins]]
repo = 'Shougo/denite.nvim'

# Terminal
[[plugins]]
repo = 'kassio/neoterm'
if   = 'has("nvim")'

# Ansible
[[plugins]]
repo  = 'pearofducks/ansible-vim'
